// <auto-generated />
namespace FMI.WeAzure.Boxing.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReplaceIDwithusernamekey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReplaceIDwithusernamekey));
        
        string IMigrationMetadata.Id
        {
            get { return "201602112048414_Replace ID with username key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
